# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc/proto/assistant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc/proto/assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19rpc/proto/assistant.proto\x12\tassistant\"S\n\x10\x41ssistantRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_view\x18\x02 \x01(\t\x12\x18\n\x10\x63urrent_email_id\x18\x03 \x01(\t\"(\n\x11\x41ssistantResponse\x12\x13\n\x0b\x61\x63tion_json\x18\x01 \x01(\t2_\n\x10\x41ssistantService\x12K\n\x0eProcessMessage\x12\x1b.assistant.AssistantRequest\x1a\x1c.assistant.AssistantResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.proto.assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSISTANTREQUEST']._serialized_start=40
  _globals['_ASSISTANTREQUEST']._serialized_end=123
  _globals['_ASSISTANTRESPONSE']._serialized_start=125
  _globals['_ASSISTANTRESPONSE']._serialized_end=165
  _globals['_ASSISTANTSERVICE']._serialized_start=167
  _globals['_ASSISTANTSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
