# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.proto import mail_pb2 as rpc_dot_proto_dot_mail__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc/proto/mail_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInbox = channel.unary_unary(
                '/mail.MailService/GetInbox',
                request_serializer=rpc_dot_proto_dot_mail__pb2.GetInboxRequest.SerializeToString,
                response_deserializer=rpc_dot_proto_dot_mail__pb2.GetInboxResponse.FromString,
                _registered_method=True)
        self.GetSent = channel.unary_unary(
                '/mail.MailService/GetSent',
                request_serializer=rpc_dot_proto_dot_mail__pb2.GetSentRequest.SerializeToString,
                response_deserializer=rpc_dot_proto_dot_mail__pb2.GetSentResponse.FromString,
                _registered_method=True)
        self.GetEmailById = channel.unary_unary(
                '/mail.MailService/GetEmailById',
                request_serializer=rpc_dot_proto_dot_mail__pb2.GetEmailByIdRequest.SerializeToString,
                response_deserializer=rpc_dot_proto_dot_mail__pb2.GetEmailByIdResponse.FromString,
                _registered_method=True)
        self.SendEmail = channel.unary_unary(
                '/mail.MailService/SendEmail',
                request_serializer=rpc_dot_proto_dot_mail__pb2.SendEmailRequest.SerializeToString,
                response_deserializer=rpc_dot_proto_dot_mail__pb2.SendEmailResponse.FromString,
                _registered_method=True)
        self.SearchEmails = channel.unary_unary(
                '/mail.MailService/SearchEmails',
                request_serializer=rpc_dot_proto_dot_mail__pb2.SearchEmailsRequest.SerializeToString,
                response_deserializer=rpc_dot_proto_dot_mail__pb2.SearchEmailsResponse.FromString,
                _registered_method=True)


class MailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmailById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEmails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInbox,
                    request_deserializer=rpc_dot_proto_dot_mail__pb2.GetInboxRequest.FromString,
                    response_serializer=rpc_dot_proto_dot_mail__pb2.GetInboxResponse.SerializeToString,
            ),
            'GetSent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSent,
                    request_deserializer=rpc_dot_proto_dot_mail__pb2.GetSentRequest.FromString,
                    response_serializer=rpc_dot_proto_dot_mail__pb2.GetSentResponse.SerializeToString,
            ),
            'GetEmailById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmailById,
                    request_deserializer=rpc_dot_proto_dot_mail__pb2.GetEmailByIdRequest.FromString,
                    response_serializer=rpc_dot_proto_dot_mail__pb2.GetEmailByIdResponse.SerializeToString,
            ),
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=rpc_dot_proto_dot_mail__pb2.SendEmailRequest.FromString,
                    response_serializer=rpc_dot_proto_dot_mail__pb2.SendEmailResponse.SerializeToString,
            ),
            'SearchEmails': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEmails,
                    request_deserializer=rpc_dot_proto_dot_mail__pb2.SearchEmailsRequest.FromString,
                    response_serializer=rpc_dot_proto_dot_mail__pb2.SearchEmailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mail.MailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mail.MailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mail.MailService/GetInbox',
            rpc_dot_proto_dot_mail__pb2.GetInboxRequest.SerializeToString,
            rpc_dot_proto_dot_mail__pb2.GetInboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mail.MailService/GetSent',
            rpc_dot_proto_dot_mail__pb2.GetSentRequest.SerializeToString,
            rpc_dot_proto_dot_mail__pb2.GetSentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmailById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mail.MailService/GetEmailById',
            rpc_dot_proto_dot_mail__pb2.GetEmailByIdRequest.SerializeToString,
            rpc_dot_proto_dot_mail__pb2.GetEmailByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mail.MailService/SendEmail',
            rpc_dot_proto_dot_mail__pb2.SendEmailRequest.SerializeToString,
            rpc_dot_proto_dot_mail__pb2.SendEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEmails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mail.MailService/SearchEmails',
            rpc_dot_proto_dot_mail__pb2.SearchEmailsRequest.SerializeToString,
            rpc_dot_proto_dot_mail__pb2.SearchEmailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
