# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc/proto/mail.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc/proto/mail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14rpc/proto/mail.proto\x12\x04mail\"t\n\x05\x45mail\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0f\n\x07snippet\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\x12\x11\n\tis_unread\x18\x07 \x01(\x08\":\n\x0fGetInboxRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"H\n\x10GetInboxResponse\x12\x1b\n\x06\x65mails\x18\x01 \x03(\x0b\x32\x0b.mail.Email\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"9\n\x0eGetSentRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"G\n\x0fGetSentResponse\x12\x1b\n\x06\x65mails\x18\x01 \x03(\x0b\x32\x0b.mail.Email\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"\'\n\x13GetEmailByIdRequest\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\"A\n\x14GetEmailByIdResponse\x12\x1a\n\x05\x65mail\x18\x01 \x01(\x0b\x32\x0b.mail.Email\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"=\n\x10SendEmailRequest\x12\n\n\x02to\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"2\n\x11SendEmailResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\"M\n\x13SearchEmailsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"L\n\x14SearchEmailsResponse\x12\x1b\n\x06\x65mails\x18\x01 \x03(\x0b\x32\x0b.mail.Email\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xcc\x02\n\x0bMailService\x12\x39\n\x08GetInbox\x12\x15.mail.GetInboxRequest\x1a\x16.mail.GetInboxResponse\x12\x36\n\x07GetSent\x12\x14.mail.GetSentRequest\x1a\x15.mail.GetSentResponse\x12\x45\n\x0cGetEmailById\x12\x19.mail.GetEmailByIdRequest\x1a\x1a.mail.GetEmailByIdResponse\x12<\n\tSendEmail\x12\x16.mail.SendEmailRequest\x1a\x17.mail.SendEmailResponse\x12\x45\n\x0cSearchEmails\x12\x19.mail.SearchEmailsRequest\x1a\x1a.mail.SearchEmailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.proto.mail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAIL']._serialized_start=30
  _globals['_EMAIL']._serialized_end=146
  _globals['_GETINBOXREQUEST']._serialized_start=148
  _globals['_GETINBOXREQUEST']._serialized_end=206
  _globals['_GETINBOXRESPONSE']._serialized_start=208
  _globals['_GETINBOXRESPONSE']._serialized_end=280
  _globals['_GETSENTREQUEST']._serialized_start=282
  _globals['_GETSENTREQUEST']._serialized_end=339
  _globals['_GETSENTRESPONSE']._serialized_start=341
  _globals['_GETSENTRESPONSE']._serialized_end=412
  _globals['_GETEMAILBYIDREQUEST']._serialized_start=414
  _globals['_GETEMAILBYIDREQUEST']._serialized_end=453
  _globals['_GETEMAILBYIDRESPONSE']._serialized_start=455
  _globals['_GETEMAILBYIDRESPONSE']._serialized_end=520
  _globals['_SENDEMAILREQUEST']._serialized_start=522
  _globals['_SENDEMAILREQUEST']._serialized_end=583
  _globals['_SENDEMAILRESPONSE']._serialized_start=585
  _globals['_SENDEMAILRESPONSE']._serialized_end=635
  _globals['_SEARCHEMAILSREQUEST']._serialized_start=637
  _globals['_SEARCHEMAILSREQUEST']._serialized_end=714
  _globals['_SEARCHEMAILSRESPONSE']._serialized_start=716
  _globals['_SEARCHEMAILSRESPONSE']._serialized_end=792
  _globals['_MAILSERVICE']._serialized_start=795
  _globals['_MAILSERVICE']._serialized_end=1127
# @@protoc_insertion_point(module_scope)
